### ISSUE TITLE
ActiveRecord::NoEnvironmentInSchemaError:

### ISSUE THREAD

**Issue by romenigld** [radar/twist#18]
Just to warn, every time when add a new attribute on the table accounts, it's complaining an error when I try to run the rspec command.
like now I try to create a owner_id and then a subdomain. 
I have this error:
```
$ rspec spec/features/accounts/sign_up_spec.rb
rails aborted!
ActiveRecord::NoEnvironmentInSchemaError:

Environment data not found in the schema. To resolve this issue, run:

        bin/rails db:environment:set RAILS_ENV=test
```
So when I run  `bin/rails db:environment:set RAILS_ENV=test` the rspec works good, again and I was posible continue.
When occur this in the first time when I create the owner_id I do that and then I drop, create and load the database:
```
bundle exec rake db:drop RAILS_ENV=test
bundle exec rake db:create RAILS_ENV=test
bundle exec rake db:schema:load RAILS_ENV=test
``` 
But this still occurring. You know something for do and not occur anymore??

**Comment by twist-fetcher** [comment]
This one was happening because I had not configured database_cleaner correctly. I have a fix on my local master branch for this that I will push up to GitHub tomorrow and share with you. It should make this error go away.

**Comment by radar** [comment]
This one is now fixed by https://github.com/radar/twist/commit/98174ed9a7f64918c637fdc8c530f4f372e2b444.

**Comment by romenigld** [comment]
Sorry I'm not expert in git, so, I do this firstly I commit my last changes for do this rebase:
`git pull --rebase origin master`
So I run the rspec and works fine. Then I commit again for continue the ebook. And when I try to push for my personal GitHub account I have this error:
```
git push personal master
To github.com:romenigld/twist
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:romenigld/twist'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
➜  twist git:(master) git pull
remote: Counting objects: 186, done.
remote: Compressing objects: 100% (165/165), done.
remote: Total 186 (delta 100), reused 6 (delta 6), pack-reused 6
Receiving objects: 100% (186/186), 33.78 KiB | 10.00 KiB/s, done.
Resolving deltas: 100% (103/103), completed with 6 local objects.
From github.com:radar/twist
 * [new branch]      mtwr-walkthrough -> origin/mtwr-walkthrough
Already up-to-date.
git push personal origin master
fatal: refs/remotes/origin/HEAD cannot be resolved to branch.
git push -f personal origin master
fatal: refs/remotes/origin/HEAD cannot be resolved to branch.
git remote -v
origin	git@github.com:radar/twist (fetch)
origin	git@github.com:radar/twist (push)
personal	git@github.com:romenigld/twist (fetch)
personal	git@github.com:romenigld/twist (push)
```
Can you help me with this? I don't want to push to your repository or do something bad.

**Comment by radar** [comment]
Looks like you may not be checked out to a branch there. Try:

```
git checkout master
git pull --rebase origin master
git push personal master
```

You won't be able to push to my repo as you don't have access, so don't stress about that :) Even if you did have access, I think I know how to undo it anyway. No problem!

**Comment by romenigld** [comment]
I just have the branch master
I try these commands and the error persist.
```
 git branch
* master
➜  twist git:(master) git checkout master
Already on 'master'
Your branch is ahead of 'origin/master' by 7 commits.
  (use "git push" to publish your local commits)
➜  twist git:(master) git pull --rebase origin master
From github.com:radar/twist
 * branch            master     -> FETCH_HEAD
Current branch master is up to date.
➜  twist git:(master) git push personal master
To github.com:romenigld/twist
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:romenigld/twist'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by romenigld** [comment]
I searched on stack overflow and now work's.
What I needed to do was  `git pull` first and then do a push with `--force` flag.
look:

```
$ git pull
remote: Counting objects: 43, done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 43 (delta 11), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (43/43), done.
From github.com:radar/twist
 + c61be89...41dd1df mtwr-walkthrough -> origin/mtwr-walkthrough  (forced update)
Already up-to-date.
➜  twist git:(master) $ git push personal master
To github.com:romenigld/twist
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:romenigld/twist'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
➜  twist git:(master) $ git push --force personal master
Counting objects: 183, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (163/163), done.
Writing objects: 100% (183/183), 23.27 KiB | 0 bytes/s, done.
Total 183 (delta 87), reused 33 (delta 3)
remote: Resolving deltas: 100% (87/87), completed with 23 local objects.
To github.com:romenigld/twist
 + ea01cf9...42acb83 master -> master (forced update)
```
Thank's anyway Ryan Bigg!
